/* Camping Paradis — dictionnaire EN
   Clé = texte français exact (espaces normalisés). */
window.CP_I18N = window.CP_I18N || {};
window.CP_I18N['en'] = {
  "Installer l'application": "Install the app",
  "Accédez à toutes les infos du camping en un clic, même sans connexion !": "Access all the campsite info in one click, even offline!",
  "Appuie sur le bouton": "Tap the button",
  "Partager": "Share",
  "⬆️ en bas de Safari": "⬆️ at the bottom of Safari",
  "Sélectionne": "Select",
  "\"Sur l'écran d'accueil\"": "\"Add to Home Screen\"",
  "Appuie sur": "Tap",
  "\"Ajouter\"": "\"Add\"",
  "en haut à droite": "at the top right",
  "Appuie sur le menu": "Tap the menu",
  "\"Ajouter à l'écran d'accueil\"": "\"Add to Home screen\"",
  "Confirme en appuyant sur": "Confirm by tapping",
  "✓ J'ai compris !": "✓ Got it!",
  "Continuer sans installer": "Continue without installing",
  "📱 Installer l'App": "📱 Install the App",
  "Matafelon-Granges · Aujourd'hui": "Matafelon-Granges · Today",
  "Aujourd'hui": "Today",
  "Chargement...": "Loading...",
  "Voir plus →": "See more →",
  "Bon plan du moment": "Today's special deal",
  "Météo indisponible": "Weather unavailable",
  "Ciel dégagé": "Clear sky",
  "Principalement dégagé": "Mostly clear",
  "Partiellement nuageux": "Partly cloudy",
  "Couvert": "Overcast",
  "Brouillard": "Fog",
  "Brouillard givrant": "Freezing fog",
  "Bruine légère": "Light drizzle",
  "Bruine modérée": "Moderate drizzle",
  "Bruine dense": "Dense drizzle",
  "Pluie légère": "Light rain",
  "Pluie modérée": "Moderate rain",
  "Pluie forte": "Heavy rain",
  "Averses légères": "Light showers",
  "Averses modérées": "Moderate showers",
  "Averses fortes": "Heavy showers",
  "Neige légère": "Light snow",
  "Neige modérée": "Moderate snow",
  "Neige forte": "Heavy snow",
  "Averses de neige": "Snow showers",
  "Averses de neige fortes": "Heavy snow showers",
  "Orage": "Thunderstorm",
  "Orage avec grêle": "Thunderstorm with hail",
  "Orage violent": "Severe thunderstorm",
  "Variable": "Changeable",
  "Vie au camping": "Campsite life",
  "Horaires du Camping": "Campsite opening hours",
  "Réception, piscine, animations et services": "Reception, pool, entertainment and services",
  "Plan du camping": "Campsite map",
  "Retrouvez votre emplacement et les équipements": "Find your pitch and the facilities",
  "Tout savoir pour votre arrivée et départ": "Everything you need to know for arrival and departure",
  "Pot d'accueil": "Welcome drink",
  "Rejoignez-nous pour un verre de bienvenue": "Join us for a welcome drink",
  "Service optionnel": "Optional service",
  "Ménage fin de séjour": "End-of-stay cleaning",
  "Partez l'esprit libre — on s'occupe de tout": "Leave worry-free — we take care of everything",
  "Service disponible sur demande": "Service available on request",
  "Tarifs forfaitaires": "Flat rates",
  "Mobil-home 2 ch.": "2-bedroom mobile home",
  "Mobil-home 3 ch.": "3-bedroom mobile home",
  "Inclus dans la prestation": "Included in the service",
  "Nettoyage complet du logement": "Full cleaning of the accommodation",
  "Sanitaires et cuisine": "Bathroom and kitchen",
  "Gestion des déchets": "Waste disposal",
  "Confirmation par la réception": "Confirmation by reception",
  "N° d'emplacement *": "Pitch number *",
  "Date de départ *": "Departure date *",
  "Téléphone (optionnel)": "Phone (optional)",
  "Demander le ménage →": "Request cleaning →",
  "Annuler": "Cancel",
  "Demande envoyée !": "Request sent!",
  "Notre équipe a bien reçu votre demande.": "Our team has received your request.",
  "Nous vous confirmons le tarif exact selon votre emplacement.": "We will confirm the exact price for your pitch.",
  "Fermer": "Close",
  "Nos Services": "Our Services",
  "Kayak": "Kayaking",
  "Explorez le lac du Val d'Oignin en kayak": "Explore Lake Val d'Oignin by kayak",
  "Laverie": "Laundry",
  "Service de laverie disponible 24h/24": "Laundry service available 24/7",
  "Locations Diverses": "Equipment rental",
  "Locations diverses": "Equipment rental",
  "Barbecue, draps, kit bébé, linge de toilettes": "Barbecue, bed linen, baby kit, towels",
  "Connexion internet gratuite": "Free internet access",
  "Restauration & Bar": "Food & Bar",
  "Burgers, salades et plats du jour": "Burgers, salads and daily specials",
  "Cocktails, bières et boissons fraîches": "Cocktails, beers and cold drinks",
  "Épicerie": "Grocery shop",
  "Produits essentiels": "Everyday essentials",
  "Petit-Déjeuner": "Breakfast",
  "Petit-déjeuner": "Breakfast",
  "Pain frais et viennoiseries chaque matin": "Fresh bread and pastries every morning",
  "Autour du camping": "Around the campsite",
  "Activités à faire": "Things to do",
  "Kayak, randonnées, sports et loisirs en plein air": "Kayaking, hiking, sports and outdoor leisure",
  "Restaurants": "Restaurants",
  "Les meilleures tables autour du camping": "The best restaurants near the campsite",
  "À visiter": "Places to visit",
  "Gorges de l'Ain, viaduc, cascade et villages": "Ain gorges, viaduct, waterfall and villages",
  "Randonnées et Balades": "Hikes and Walks",
  "Sentiers balisés pour tous les niveaux": "Marked trails for all levels",
  "Marchés": "Markets",
  "Producteurs locaux et marchés de la région": "Local producers and regional markets",
  "Commerces": "Shops",
  "Supermarchés et commerces à proximité": "Supermarkets and shops nearby",
  "Animations": "Entertainment",
  "Programme de la semaine": "This week's programme",
  "Activités, soirées et événements à ne pas manquer": "Activities, evenings and events not to be missed",
  "Club enfants": "Kids' club",
  "Ateliers et aventures pour les 6-12 ans": "Workshops and adventures for ages 6–12",
  "Montez sur scène et brillez devant tout le camping !": "Get on stage and shine in front of the whole campsite!",
  "Circulation": "Getting around",
  "Horaires de la barrière": "Barrier opening hours",
  "Entrées et sorties du camping : plages horaires": "Campsite entry and exit times",
  "Véhicule électrique": "Electric vehicle",
  "Recharge disponible sur site — infos et tarifs": "Charging available on site — info and prices",
  "Signaler un problème": "Report a problem",
  "Notre équipe intervient dans les plus brefs délais.": "Our team will respond as quickly as possible.",
  "Décrivez votre situation et nous revenons vers vous rapidement.": "Describe your situation and we will get back to you quickly.",
  "Type de problème *": "Type of problem *",
  "Choisir...": "Choose...",
  "🚿 Sanitaires": "🚿 Sanitary facilities",
  "🔌 Électricité / Eau": "🔌 Electricity / Water",
  "🔊 Nuisances sonores": "🔊 Noise nuisance",
  "🗑️ Propreté": "🗑️ Cleanliness",
  "🌿 Végétation / Terrain": "🌿 Vegetation / Grounds",
  "🚗 Circulation / Barrière": "🚗 Traffic / Barrier",
  "🍽️ Restaurant / Épicerie": "🍽️ Restaurant / Shop",
  "🏊 Piscine": "🏊 Pool",
  "❓ Autre": "❓ Other",
  "Description *": "Description *",
  "Envoyer le signalement →": "Send report →",
  "Signalement envoyé !": "Report sent!",
  "Notre équipe a bien reçu votre message et interviendra dans les plus brefs délais.": "Our team has received your message and will respond as soon as possible.",
  "Merci de nous aider à améliorer votre séjour 🙏": "Thank you for helping us improve your stay 🙏",
  "© 2026 Tous droits réservés.": "© 2026 All rights reserved.",
  "Assistant Camping": "Campsite Assistant",
  "Réponses immédiates": "Instant answers",
  "Réception": "Reception",
  "Voir les horaires": "See opening hours",
  "Passer en mode sombre": "Switch to dark mode",
  "Passer en mode clair": "Switch to light mode",
  "Appeler la réception": "Call reception",
  "Changer le thème": "Change theme",
  "Effacer": "Clear",
  "Envoyer": "Send",
  "Ouvrir l'assistant": "Open the assistant",
  "Rechercher dans l'application": "Search the app",
  "Décrivez votre problème en quelques mots...": "Describe your problem in a few words...",
  "Ex : 42": "E.g. 42",
  "Pour confirmation": "For confirmation",
  "Pour qu'on vous rappelle si besoin": "So we can call you back if needed",
  "Rechercher une page, un service, une activité…": "Search for a page, service or activity…",
  "Écrivez votre question…": "Type your question…",
  "Numéro uniquement": "Numbers only"
};
