/* Camping Paradis — dictionnaire ES
   Clé = texte français exact (espaces normalisés). */
window.CP_I18N = window.CP_I18N || {};
window.CP_I18N['es'] = {
  "Installer l'application": "Instalar la aplicación",
  "Accédez à toutes les infos du camping en un clic, même sans connexion !": "Accede a toda la información del camping con un clic, ¡incluso sin conexión!",
  "Appuie sur le bouton": "Pulsa el botón",
  "Partager": "Compartir",
  "⬆️ en bas de Safari": "⬆️ abajo en Safari",
  "Sélectionne": "Selecciona",
  "\"Sur l'écran d'accueil\"": "\"Añadir a pantalla de inicio\"",
  "Appuie sur": "Pulsa",
  "\"Ajouter\"": "\"Añadir\"",
  "en haut à droite": "arriba a la derecha",
  "Appuie sur le menu": "Pulsa el menú",
  "\"Ajouter à l'écran d'accueil\"": "\"Añadir a pantalla de inicio\"",
  "Confirme en appuyant sur": "Confirma pulsando",
  "✓ J'ai compris !": "✓ ¡Entendido!",
  "Continuer sans installer": "Continuar sin instalar",
  "📱 Installer l'App": "📱 Instalar la App",
  "Matafelon-Granges · Aujourd'hui": "Matafelon-Granges · Hoy",
  "Aujourd'hui": "Hoy",
  "Chargement...": "Cargando...",
  "Voir plus →": "Ver más →",
  "Bon plan du moment": "Oferta del momento",
  "Météo indisponible": "Tiempo no disponible",
  "Ciel dégagé": "Cielo despejado",
  "Principalement dégagé": "Mayormente despejado",
  "Partiellement nuageux": "Parcialmente nublado",
  "Couvert": "Cubierto",
  "Brouillard": "Niebla",
  "Brouillard givrant": "Niebla helada",
  "Bruine légère": "Llovizna ligera",
  "Bruine modérée": "Llovizna moderada",
  "Bruine dense": "Llovizna densa",
  "Pluie légère": "Lluvia ligera",
  "Pluie modérée": "Lluvia moderada",
  "Pluie forte": "Lluvia fuerte",
  "Averses légères": "Chubascos ligeros",
  "Averses modérées": "Chubascos moderados",
  "Averses fortes": "Chubascos fuertes",
  "Neige légère": "Nieve ligera",
  "Neige modérée": "Nieve moderada",
  "Neige forte": "Nieve fuerte",
  "Averses de neige": "Chubascos de nieve",
  "Averses de neige fortes": "Chubascos de nieve fuertes",
  "Orage": "Tormenta",
  "Orage avec grêle": "Tormenta con granizo",
  "Orage violent": "Tormenta fuerte",
  "Variable": "Variable",
  "Vie au camping": "Vida en el camping",
  "Horaires du Camping": "Horarios del camping",
  "Réception, piscine, animations et services": "Recepción, piscina, animación y servicios",
  "Plan du camping": "Plano del camping",
  "Retrouvez votre emplacement et les équipements": "Encuentra tu parcela y las instalaciones",
  "Tout savoir pour votre arrivée et départ": "Todo sobre tu llegada y salida",
  "Pot d'accueil": "Copa de bienvenida",
  "Rejoignez-nous pour un verre de bienvenue": "Acompáñanos a tomar una copa de bienvenida",
  "Service optionnel": "Servicio opcional",
  "Ménage fin de séjour": "Limpieza de fin de estancia",
  "Partez l'esprit libre — on s'occupe de tout": "Márchate sin preocupaciones: nosotros nos encargamos de todo",
  "Service disponible sur demande": "Servicio disponible bajo petición",
  "Tarifs forfaitaires": "Tarifas fijas",
  "Mobil-home 2 ch.": "Mobil home 2 hab.",
  "Mobil-home 3 ch.": "Mobil home 3 hab.",
  "Inclus dans la prestation": "Incluido en el servicio",
  "Nettoyage complet du logement": "Limpieza completa del alojamiento",
  "Sanitaires et cuisine": "Baño y cocina",
  "Gestion des déchets": "Gestión de residuos",
  "Confirmation par la réception": "Confirmación por parte de la recepción",
  "N° d'emplacement *": "N.º de parcela *",
  "Date de départ *": "Fecha de salida *",
  "Téléphone (optionnel)": "Teléfono (opcional)",
  "Demander le ménage →": "Solicitar limpieza →",
  "Annuler": "Cancelar",
  "Demande envoyée !": "¡Solicitud enviada!",
  "Notre équipe a bien reçu votre demande.": "Nuestro equipo ha recibido tu solicitud.",
  "Nous vous confirmons le tarif exact selon votre emplacement.": "Te confirmaremos la tarifa exacta según tu parcela.",
  "Fermer": "Cerrar",
  "Nos Services": "Nuestros servicios",
  "Kayak": "Kayak",
  "Explorez le lac du Val d'Oignin en kayak": "Explora el lago de Val d'Oignin en kayak",
  "Laverie": "Lavandería",
  "Service de laverie disponible 24h/24": "Servicio de lavandería disponible 24 h",
  "Locations Diverses": "Alquileres",
  "Locations diverses": "Alquileres",
  "Barbecue, draps, kit bébé, linge de toilettes": "Barbacoa, sábanas, kit de bebé, toallas",
  "Connexion internet gratuite": "Conexión a internet gratuita",
  "Restauration & Bar": "Restauración y bar",
  "Burgers, salades et plats du jour": "Hamburguesas, ensaladas y platos del día",
  "Cocktails, bières et boissons fraîches": "Cócteles, cervezas y bebidas frías",
  "Épicerie": "Tienda",
  "Produits essentiels": "Productos básicos",
  "Petit-Déjeuner": "Desayuno",
  "Petit-déjeuner": "Desayuno",
  "Pain frais et viennoiseries chaque matin": "Pan fresco y bollería cada mañana",
  "Autour du camping": "Alrededores del camping",
  "Activités à faire": "Actividades",
  "Kayak, randonnées, sports et loisirs en plein air": "Kayak, senderismo, deportes y ocio al aire libre",
  "Restaurants": "Restaurantes",
  "Les meilleures tables autour du camping": "Los mejores restaurantes cerca del camping",
  "À visiter": "Lugares para visitar",
  "Gorges de l'Ain, viaduc, cascade et villages": "Gargantas del Ain, viaducto, cascada y pueblos",
  "Randonnées et Balades": "Senderismo y paseos",
  "Sentiers balisés pour tous les niveaux": "Senderos señalizados para todos los niveles",
  "Marchés": "Mercados",
  "Producteurs locaux et marchés de la région": "Productores locales y mercados de la región",
  "Commerces": "Comercios",
  "Supermarchés et commerces à proximité": "Supermercados y comercios cercanos",
  "Animations": "Animación",
  "Programme de la semaine": "Programa de la semana",
  "Activités, soirées et événements à ne pas manquer": "Actividades, veladas y eventos que no te puedes perder",
  "Club enfants": "Club infantil",
  "Ateliers et aventures pour les 6-12 ans": "Talleres y aventuras para niños de 6 a 12 años",
  "Montez sur scène et brillez devant tout le camping !": "¡Súbete al escenario y brilla ante todo el camping!",
  "Circulation": "Circulación",
  "Horaires de la barrière": "Horarios de la barrera",
  "Entrées et sorties du camping : plages horaires": "Entradas y salidas del camping: franjas horarias",
  "Véhicule électrique": "Vehículo eléctrico",
  "Recharge disponible sur site — infos et tarifs": "Recarga disponible en el camping: información y tarifas",
  "Signaler un problème": "Informar de un problema",
  "Notre équipe intervient dans les plus brefs délais.": "Nuestro equipo intervendrá lo antes posible.",
  "Décrivez votre situation et nous revenons vers vous rapidement.": "Describe tu situación y te responderemos rápidamente.",
  "Type de problème *": "Tipo de problema *",
  "Choisir...": "Elegir...",
  "🚿 Sanitaires": "🚿 Sanitarios",
  "🔌 Électricité / Eau": "🔌 Electricidad / Agua",
  "🔊 Nuisances sonores": "🔊 Ruidos molestos",
  "🗑️ Propreté": "🗑️ Limpieza",
  "🌿 Végétation / Terrain": "🌿 Vegetación / Terreno",
  "🚗 Circulation / Barrière": "🚗 Circulación / Barrera",
  "🍽️ Restaurant / Épicerie": "🍽️ Restaurante / Tienda",
  "🏊 Piscine": "🏊 Piscina",
  "❓ Autre": "❓ Otro",
  "Description *": "Descripción *",
  "Envoyer le signalement →": "Enviar el aviso →",
  "Signalement envoyé !": "¡Aviso enviado!",
  "Notre équipe a bien reçu votre message et interviendra dans les plus brefs délais.": "Nuestro equipo ha recibido tu mensaje e intervendrá lo antes posible.",
  "Merci de nous aider à améliorer votre séjour 🙏": "Gracias por ayudarnos a mejorar tu estancia 🙏",
  "© 2026 Tous droits réservés.": "© 2026 Todos los derechos reservados.",
  "Assistant Camping": "Asistente del camping",
  "Réponses immédiates": "Respuestas inmediatas",
  "Réception": "Recepción",
  "Voir les horaires": "Ver horarios",
  "Passer en mode sombre": "Activar modo oscuro",
  "Passer en mode clair": "Activar modo claro",
  "Appeler la réception": "Llamar a recepción",
  "Changer le thème": "Cambiar tema",
  "Effacer": "Borrar",
  "Envoyer": "Enviar",
  "Ouvrir l'assistant": "Abrir el asistente",
  "Rechercher dans l'application": "Buscar en la aplicación",
  "Décrivez votre problème en quelques mots...": "Describe tu problema en pocas palabras...",
  "Ex : 42": "Ej.: 42",
  "Pour confirmation": "Para confirmación",
  "Pour qu'on vous rappelle si besoin": "Para poder llamarte si es necesario",
  "Rechercher une page, un service, une activité…": "Busca una página, un servicio o una actividad…",
  "Écrivez votre question…": "Escribe tu pregunta…",
  "Numéro uniquement": "Solo números"
};
