/* Camping Paradis — dictionnaire NL
   Clé = texte français exact (espaces normalisés). */
window.CP_I18N = window.CP_I18N || {};
window.CP_I18N['nl'] = {
  "Installer l'application": "Installeer de app",
  "Accédez à toutes les infos du camping en un clic, même sans connexion !": "Alle camping-info met één klik, zelfs zonder internet!",
  "Appuie sur le bouton": "Tik op de knop",
  "Partager": "Delen",
  "⬆️ en bas de Safari": "⬆️ onderaan in Safari",
  "Sélectionne": "Selecteer",
  "\"Sur l'écran d'accueil\"": "\"Zet op beginscherm\"",
  "Appuie sur": "Tik op",
  "\"Ajouter\"": "\"Voeg toe\"",
  "en haut à droite": "rechtsboven",
  "Appuie sur le menu": "Tik op het menu",
  "\"Ajouter à l'écran d'accueil\"": "\"Toevoegen aan startscherm\"",
  "Confirme en appuyant sur": "Bevestig door te tikken op",
  "✓ J'ai compris !": "✓ Begrepen!",
  "Continuer sans installer": "Doorgaan zonder installeren",
  "📱 Installer l'App": "📱 App installeren",
  "Matafelon-Granges · Aujourd'hui": "Matafelon-Granges · Vandaag",
  "Aujourd'hui": "Vandaag",
  "Chargement...": "Laden...",
  "Voir plus →": "Meer zien →",
  "Bon plan du moment": "Aanbieding van het moment",
  "Météo indisponible": "Weer niet beschikbaar",
  "Ciel dégagé": "Heldere lucht",
  "Principalement dégagé": "Overwegend helder",
  "Partiellement nuageux": "Gedeeltelijk bewolkt",
  "Couvert": "Bewolkt",
  "Brouillard": "Mist",
  "Brouillard givrant": "Aanvriezende mist",
  "Bruine légère": "Lichte motregen",
  "Bruine modérée": "Matige motregen",
  "Bruine dense": "Dichte motregen",
  "Pluie légère": "Lichte regen",
  "Pluie modérée": "Matige regen",
  "Pluie forte": "Zware regen",
  "Averses légères": "Lichte buien",
  "Averses modérées": "Matige buien",
  "Averses fortes": "Zware buien",
  "Neige légère": "Lichte sneeuw",
  "Neige modérée": "Matige sneeuw",
  "Neige forte": "Zware sneeuw",
  "Averses de neige": "Sneeuwbuien",
  "Averses de neige fortes": "Zware sneeuwbuien",
  "Orage": "Onweer",
  "Orage avec grêle": "Onweer met hagel",
  "Orage violent": "Zwaar onweer",
  "Variable": "Wisselvallig",
  "Vie au camping": "Het campingleven",
  "Horaires du Camping": "Openingstijden camping",
  "Réception, piscine, animations et services": "Receptie, zwembad, animatie en diensten",
  "Plan du camping": "Plattegrond van de camping",
  "Retrouvez votre emplacement et les équipements": "Vind uw plaats en de voorzieningen",
  "Tout savoir pour votre arrivée et départ": "Alles over uw aankomst en vertrek",
  "Pot d'accueil": "Welkomstborrel",
  "Rejoignez-nous pour un verre de bienvenue": "Kom langs voor een welkomstdrankje",
  "Service optionnel": "Optionele dienst",
  "Ménage fin de séjour": "Eindschoonmaak",
  "Partez l'esprit libre — on s'occupe de tout": "Vertrek zonder zorgen — wij regelen alles",
  "Service disponible sur demande": "Dienst beschikbaar op aanvraag",
  "Tarifs forfaitaires": "Vaste tarieven",
  "Mobil-home 2 ch.": "Stacaravan 2 slaapkamers",
  "Mobil-home 3 ch.": "Stacaravan 3 slaapkamers",
  "Inclus dans la prestation": "Inbegrepen in de dienst",
  "Nettoyage complet du logement": "Volledige schoonmaak van de accommodatie",
  "Sanitaires et cuisine": "Sanitair en keuken",
  "Gestion des déchets": "Afvalverwerking",
  "Confirmation par la réception": "Bevestiging door de receptie",
  "N° d'emplacement *": "Plaatsnummer *",
  "Date de départ *": "Vertrekdatum *",
  "Téléphone (optionnel)": "Telefoon (optioneel)",
  "Demander le ménage →": "Schoonmaak aanvragen →",
  "Annuler": "Annuleren",
  "Demande envoyée !": "Aanvraag verzonden!",
  "Notre équipe a bien reçu votre demande.": "Ons team heeft uw aanvraag ontvangen.",
  "Nous vous confirmons le tarif exact selon votre emplacement.": "Wij bevestigen het exacte tarief voor uw plaats.",
  "Fermer": "Sluiten",
  "Nos Services": "Onze diensten",
  "Kayak": "Kajak",
  "Explorez le lac du Val d'Oignin en kayak": "Verken het meer van Val d'Oignin per kajak",
  "Laverie": "Wasserette",
  "Service de laverie disponible 24h/24": "Wasservice 24 uur per dag beschikbaar",
  "Locations Diverses": "Diverse verhuur",
  "Locations diverses": "Diverse verhuur",
  "Barbecue, draps, kit bébé, linge de toilettes": "Barbecue, beddengoed, babykit, handdoeken",
  "Connexion internet gratuite": "Gratis internetverbinding",
  "Restauration & Bar": "Eten & Bar",
  "Burgers, salades et plats du jour": "Burgers, salades en dagschotels",
  "Cocktails, bières et boissons fraîches": "Cocktails, bier en frisdrank",
  "Épicerie": "Winkeltje",
  "Produits essentiels": "Dagelijkse boodschappen",
  "Petit-Déjeuner": "Ontbijt",
  "Petit-déjeuner": "Ontbijt",
  "Pain frais et viennoiseries chaque matin": "Vers brood en croissants elke ochtend",
  "Autour du camping": "Rondom de camping",
  "Activités à faire": "Activiteiten",
  "Kayak, randonnées, sports et loisirs en plein air": "Kajakken, wandelen, sport en buitenactiviteiten",
  "Restaurants": "Restaurants",
  "Les meilleures tables autour du camping": "De beste restaurants in de buurt",
  "À visiter": "Bezienswaardigheden",
  "Gorges de l'Ain, viaduc, cascade et villages": "Kloven van de Ain, viaduct, waterval en dorpjes",
  "Randonnées et Balades": "Wandelingen",
  "Sentiers balisés pour tous les niveaux": "Bewegwijzerde paden voor elk niveau",
  "Marchés": "Markten",
  "Producteurs locaux et marchés de la région": "Lokale producenten en streekmarkten",
  "Commerces": "Winkels",
  "Supermarchés et commerces à proximité": "Supermarkten en winkels in de buurt",
  "Animations": "Animatie",
  "Programme de la semaine": "Weekprogramma",
  "Activités, soirées et événements à ne pas manquer": "Activiteiten, avonden en evenementen die u niet mag missen",
  "Club enfants": "Kinderclub",
  "Ateliers et aventures pour les 6-12 ans": "Workshops en avonturen voor 6-12 jaar",
  "Montez sur scène et brillez devant tout le camping !": "Sta op het podium en schitter voor de hele camping!",
  "Circulation": "Verkeer",
  "Horaires de la barrière": "Openingstijden slagboom",
  "Entrées et sorties du camping : plages horaires": "In- en uitritten van de camping: tijdsloten",
  "Véhicule électrique": "Elektrische auto",
  "Recharge disponible sur site — infos et tarifs": "Opladen mogelijk op het terrein — info en tarieven",
  "Signaler un problème": "Een probleem melden",
  "Notre équipe intervient dans les plus brefs délais.": "Ons team komt zo snel mogelijk in actie.",
  "Décrivez votre situation et nous revenons vers vous rapidement.": "Beschrijf uw situatie en wij nemen snel contact met u op.",
  "Type de problème *": "Soort probleem *",
  "Choisir...": "Kies...",
  "🚿 Sanitaires": "🚿 Sanitair",
  "🔌 Électricité / Eau": "🔌 Elektriciteit / Water",
  "🔊 Nuisances sonores": "🔊 Geluidsoverlast",
  "🗑️ Propreté": "🗑️ Netheid",
  "🌿 Végétation / Terrain": "🌿 Beplanting / Terrein",
  "🚗 Circulation / Barrière": "🚗 Verkeer / Slagboom",
  "🍽️ Restaurant / Épicerie": "🍽️ Restaurant / Winkeltje",
  "🏊 Piscine": "🏊 Zwembad",
  "❓ Autre": "❓ Anders",
  "Description *": "Beschrijving *",
  "Envoyer le signalement →": "Melding versturen →",
  "Signalement envoyé !": "Melding verzonden!",
  "Notre équipe a bien reçu votre message et interviendra dans les plus brefs délais.": "Ons team heeft uw bericht ontvangen en komt zo snel mogelijk in actie.",
  "Merci de nous aider à améliorer votre séjour 🙏": "Bedankt dat u ons helpt uw verblijf te verbeteren 🙏",
  "© 2026 Tous droits réservés.": "© 2026 Alle rechten voorbehouden.",
  "Assistant Camping": "Camping-assistent",
  "Réponses immédiates": "Direct antwoord",
  "Réception": "Receptie",
  "Voir les horaires": "Bekijk de openingstijden",
  "Passer en mode sombre": "Donkere modus",
  "Passer en mode clair": "Lichte modus",
  "Appeler la réception": "Bel de receptie",
  "Changer le thème": "Thema wijzigen",
  "Effacer": "Wissen",
  "Envoyer": "Versturen",
  "Ouvrir l'assistant": "Open de assistent",
  "Rechercher dans l'application": "Zoeken in de app",
  "Décrivez votre problème en quelques mots...": "Beschrijf uw probleem in een paar woorden...",
  "Ex : 42": "Bijv. 42",
  "Pour confirmation": "Ter bevestiging",
  "Pour qu'on vous rappelle si besoin": "Zodat we u indien nodig kunnen terugbellen",
  "Rechercher une page, un service, une activité…": "Zoek een pagina, dienst of activiteit…",
  "Écrivez votre question…": "Typ uw vraag…",
  "Numéro uniquement": "Alleen cijfers"
};
